const API_ENDPOINTS = {
  LOGIN: "/api/user/login",
  SignUP: "/api/user/user-signup",
  GOOGLE_SIGN_IN: "/api/user/google-callback",
  ForgetPassword: "/api/user/forgot-password",
  VerifyOTP: "/api/user/verify-reset-otp",
  ResetNewPassword: "/api/user/reset-password",
  AiCoverLetterGenerate: "/ai/generate-cover-letter",
  FileUpload: "/api/user/upload-file",
  ResumeManager: "/ai/resume-manager",
  GetAllResumes: "/api/resume/view-resumes",
  ViewSpecificResume: (id: string) => `/api/resume/view-resume/${id}`,
  DeleteResume: "/api/resume/delete-resume",
  UpdateResume: (id: string) => `/api/resume/update-resume/${id}`,
  DownloadFile: (url: string) =>
    `/api/user/download-file?url=${encodeURIComponent(url)}`,
  AddResume: "/api/resume/add-resume",
  FileuploadResumeBuilder: "/ai/resume-builder",
  GenerateInterviewGuide: "/ai/interview-guide",
  InterviewGuideQuestions: "/ai/interview-guide-reverse_questioning",
  SaveAdvancedSearch: "/api/searchHistory/add-search-history",
  GetAllAdvancedSeardch: "/api/searchHistory/view-search-history",
  GetAdvancedSeardchSpecific: "/api/searchHistory/view-search-history",
  GetAnalyticsBySession: "/api/user/getSavedJobsByDate",
  GetAllAnalyticsForTable: "/api/user/getSavedJobsByFilters",
  GetAnalyticsByPlatform: "/api/user/savedJobsByPlatform",
  GenerateSkillsCoverLetter: "/ai/generate-skills",
  GenerateJobDescription: "/ai/generate-jed",
  GenerateAchivementDescription: "/ai/generate-ctd",
  CreateResumeBuilder: "/api/resumeBuilder/add-resume",
  UpdateResumeBuilder: "/api/resumeBuilder/update-resume",
  DeleteResumeBuilder: "/api/resumeBuilder/delete-resume",
  GetAllResumeBuilder: "/api/resumeBuilder/view-resumes",
  GetResumeBuilderById: "/api/resumeBuilder/view-resume",
  ResumeScore: "/ai/generate-rms",
  GenerateSummary: "/ai/generate-suggested-summary"
}

export default API_ENDPOINTS
